language: go
go: 1.15.x
go_import_path: github.com/snhilde/statusbar/v5

dist: bionic

env:
    - GO111MODULE=on

before_install:
    - cd v5

install:
    - go get golang.org/x/lint/golint
    - go install golang.org/x/lint/golint

script:
    - make fmt-check
    - make lint-check
