language: go
go: 1.15.x
go_import_path: github.com/snhilde/statusbar/v5

dist: bionic

env:
    - GO111MODULE=on

before_install:
    - cd v5

install:
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

script:
    - make fmt-check
    - make lint-check-source
